import { Box } from '@mui/material'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
      <Box>
        <Box sx={{
          display: "-ms-flexbox",
        }}> 
     
       </Box>
       <Box sx={{
          display: "flex",
          justifyContent: "center",
          alignItems: "center",
       }}>

       </Box>

        <main>
        {children}
        </main>
     </Box>
   
   
    
    </>

  )
}
